# Generated by Django 3.1.4 on 2021-01-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0002_gallery_main_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery_main',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ'),
        ),
    ]
