# Generated by Django 3.1.4 on 2021-01-02 11:10

import BLog.models
from django.db import migrations, models
import django.db.models.deletion
import image_optimizer.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('show', models.CharField(max_length=50, verbose_name='نام نمایشی')),
            ],
        ),
        migrations.CreateModel(
            name='Tag_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=150, verbose_name='نام تگ (لاتین)')),
                ('tag_show', models.CharField(max_length=150, verbose_name='نام تگ (فارسی)')),
            ],
            options={
                'verbose_name': 'تگ',
                'verbose_name_plural': 'تگ ها',
            },
        ),
        migrations.CreateModel(
            name='Blog_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', image_optimizer.fields.OptimizedImageField(upload_to=BLog.models.upload_image, verbose_name='عکس')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('slug', models.SlugField(default='', verbose_name='اسلاگ')),
                ('text', models.TextField(verbose_name='متن بلاگ')),
                ('is_seen', models.IntegerField(blank=True, default=0, editable=False, null=True, verbose_name='بازدید ها')),
                ('blog_tag', models.ManyToManyField(to='BLog.Tag_Model', verbose_name='تگ ها')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='BLog.category_model', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'بلاگ',
                'verbose_name_plural': 'بلاگ ها',
            },
        ),
    ]
