# Generated by Django 3.1.4 on 2021-01-03 08:14

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('BLog', '0002_blog_model_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_model',
            name='date',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
    ]
