# Generated by Django 3.1.4 on 2021-01-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BLog', '0003_auto_20210103_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_model',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
