# Generated by Django 3.1.4 on 2021-01-03 11:52

import BLog.models
from django.db import migrations
import image_optimizer.fields


class Migration(migrations.Migration):

    dependencies = [
        ('BLog', '0004_auto_20210103_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_model',
            name='image',
        ),
        migrations.AddField(
            model_name='blog_model',
            name='image_title',
            field=image_optimizer.fields.OptimizedImageField(default='image/logo.png', upload_to=BLog.models.upload_image, verbose_name='عکس نمایشی'),
        ),
        migrations.AddField(
            model_name='blog_model',
            name='inner_image',
            field=image_optimizer.fields.OptimizedImageField(default='image/logo.png', upload_to=BLog.models.upload_image, verbose_name='عکس وبلاگ'),
        ),
    ]
