# Generated by Django 3.1.4 on 2021-01-04 13:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('site_setting', '0005_auto_20210101_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='site_best_student',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ'),
            preserve_default=False,
        ),
    ]
